name: Keep Backend Awake

on:
  schedule:
    # 15 นาทีระหว่าง 02:00–14:45 UTC = 09:00–21:45 Asia/Bangkok (UTC+7)
    - cron: "*/15 2-14 * * *"
  workflow_dispatch: {}  # กดรันเองได้

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        endpoint:
          # ใส่หลาย URL ได้ (เช่น /health ของ Render)
          - "${{ secrets.WAKE_URL_1 }}"
          # - "${{ secrets.WAKE_URL_2 }}"
    steps:
      - name: Ping ${{ matrix.endpoint }}
        shell: bash
        run: |
          set -e
          echo "Pinging: ${{ matrix.endpoint }}"
          # ถ้าต้องใช้ token ให้เติม -H "Authorization: Bearer $TOKEN"
          code=$(curl -sS -o /dev/null -w "%{http_code}" -X GET \
            --max-time 20 --retry 2 --retry-delay 2 \
            "${{ matrix.endpoint }}")
          echo "HTTP $code"
          if [[ "$code" =~ ^2|3 ]]; then
            echo "Backend awake ✅"
          else
            echo "Ping failed ❌"
            exit 1
          fi
